#ifndef OPCSERVICECOMMON_GLOBAL_H
#define OPCSERVICECOMMON_GLOBAL_H

//#if defined(OPCSERVICECOMMON_LIBRARY)
#define OPCSERVICECOMMONSHARED_EXPORT  // Q_DECL_EXPORT
//#else
//#  define OPCSERVICECOMMONSHARED_EXPORT Q_DECL_IMPORT
//#endif

#endif  // OPCSERVICECOMMON_GLOBAL_H
